stack=input('enter stack elements:')
n=len(stack)
print('peep of the stack is:',stack[n-1])
print('\nElements poped from stack:')
print(stack.pop())
print(stack.pop())
print(stack.pop())
print('\nStack after elements arepoped:')
print(stack)
